### ISSUE TITLE
이슈란 무엇인가

### ISSUE THREAD

**Issue by chaebkimm** [Rosee318/aa#2]
풀 리퀘스트는 그 시점에 요청이고 수락하면 없어지는듯!

풀 리퀘스트가 많은 것이 꼭 활발하게 코웍이 이뤄진다는 것이 아닐 수 있는 것이 수락을 하지 않으면 쌓이는 것이고 수락을 빨리빨리 하면 덜 쌓이는 것

**Comment by Rosee318** [comment]
ㅇㅇ 그래서 풀리퀘스트 수락하는 시기도 고려함 
여기 오픈 프로젝트이지?

**Comment by chaebkimm** [comment]
여기는 당신의 프로젝트이당
